import type { EbagProduct } from "./types";

/**
 * Mock data representing realistic eBag.bg promotions.
 * This is used until the live scraper is connected.
 * Products, prices, and discounts reflect typical Bulgarian grocery offerings.
 */
export const MOCK_EBAG_PRODUCTS: EbagProduct[] = [
  // === PROTEIN SOURCES ===
  {
    ebagId: "chicken-breast-1",
    name: "Chicken Breast Fillet",
    nameBg: "Пилешко филе",
    category: "poultry",
    price: 11.99,
    originalPrice: 15.49,
    discountPct: 23,
    unit: "kg",
    weightGrams: 1000,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/chicken-breast",
    inStock: true,
    nutrition: { caloriesPer100g: 165, proteinPer100g: 31, carbsPer100g: 0, fatPer100g: 3.6, fiberPer100g: 0 },
  },
  {
    ebagId: "minced-meat-mixed-1",
    name: "Mixed Minced Meat",
    nameBg: "Кайма смесена",
    category: "meat",
    price: 10.49,
    originalPrice: 13.99,
    discountPct: 25,
    unit: "kg",
    weightGrams: 1000,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/minced-meat",
    inStock: true,
    nutrition: { caloriesPer100g: 250, proteinPer100g: 17, carbsPer100g: 0, fatPer100g: 20, fiberPer100g: 0 },
  },
  {
    ebagId: "salmon-fillet-1",
    name: "Salmon Fillet",
    nameBg: "Филе от сьомга",
    category: "fish",
    price: 22.99,
    originalPrice: 29.99,
    discountPct: 23,
    unit: "kg",
    weightGrams: 1000,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/salmon-fillet",
    inStock: true,
    nutrition: { caloriesPer100g: 208, proteinPer100g: 20, carbsPer100g: 0, fatPer100g: 13, fiberPer100g: 0 },
  },
  {
    ebagId: "eggs-10-1",
    name: "Free Range Eggs (10 pcs)",
    nameBg: "Яйца свободен отглед (10 бр)",
    category: "eggs",
    price: 4.29,
    originalPrice: 5.49,
    discountPct: 22,
    unit: "pcs",
    weightGrams: 600,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/eggs-10",
    inStock: true,
    nutrition: { caloriesPer100g: 155, proteinPer100g: 13, carbsPer100g: 1.1, fatPer100g: 11, fiberPer100g: 0 },
  },
  {
    ebagId: "cottage-cheese-1",
    name: "Cottage Cheese 2%",
    nameBg: "Извара 2%",
    category: "dairy",
    price: 3.49,
    originalPrice: 4.29,
    discountPct: 19,
    unit: "pcs",
    weightGrams: 500,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/cottage-cheese",
    inStock: true,
    nutrition: { caloriesPer100g: 72, proteinPer100g: 12, carbsPer100g: 2.7, fatPer100g: 2, fiberPer100g: 0 },
  },
  {
    ebagId: "greek-yogurt-1",
    name: "Greek Yogurt 2%",
    nameBg: "Гръцко кисело мляко 2%",
    category: "dairy",
    price: 2.79,
    originalPrice: 3.59,
    discountPct: 22,
    unit: "pcs",
    weightGrams: 400,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/greek-yogurt",
    inStock: true,
    nutrition: { caloriesPer100g: 59, proteinPer100g: 10, carbsPer100g: 3.6, fatPer100g: 0.7, fiberPer100g: 0 },
  },
  {
    ebagId: "white-cheese-1",
    name: "Bulgarian White Cheese (Sirene)",
    nameBg: "Сирене краве",
    category: "dairy",
    price: 8.99,
    originalPrice: 11.99,
    discountPct: 25,
    unit: "kg",
    weightGrams: 1000,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/sirene",
    inStock: true,
    nutrition: { caloriesPer100g: 264, proteinPer100g: 18, carbsPer100g: 1, fatPer100g: 21, fiberPer100g: 0 },
  },
  {
    ebagId: "canned-tuna-1",
    name: "Canned Tuna in Water",
    nameBg: "Риба тон в собствен сос",
    category: "fish",
    price: 3.29,
    originalPrice: 4.19,
    discountPct: 21,
    unit: "pcs",
    weightGrams: 185,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/canned-tuna",
    inStock: true,
    nutrition: { caloriesPer100g: 116, proteinPer100g: 26, carbsPer100g: 0, fatPer100g: 1, fiberPer100g: 0 },
  },

  // === CARB SOURCES ===
  {
    ebagId: "brown-rice-1",
    name: "Brown Rice",
    nameBg: "Кафяв ориз",
    category: "grains",
    price: 3.49,
    originalPrice: 4.49,
    discountPct: 22,
    unit: "pcs",
    weightGrams: 1000,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/brown-rice",
    inStock: true,
    nutrition: { caloriesPer100g: 362, proteinPer100g: 7.5, carbsPer100g: 76, fatPer100g: 2.7, fiberPer100g: 3.4 },
  },
  {
    ebagId: "oats-1",
    name: "Rolled Oats",
    nameBg: "Овесени ядки",
    category: "grains",
    price: 2.29,
    originalPrice: 2.99,
    discountPct: 23,
    unit: "pcs",
    weightGrams: 500,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/oats",
    inStock: true,
    nutrition: { caloriesPer100g: 389, proteinPer100g: 16.9, carbsPer100g: 66, fatPer100g: 6.9, fiberPer100g: 10.6 },
  },
  {
    ebagId: "wholegrain-bread-1",
    name: "Whole Grain Bread",
    nameBg: "Пълнозърнест хляб",
    category: "bread",
    price: 2.19,
    originalPrice: 2.79,
    discountPct: 21,
    unit: "pcs",
    weightGrams: 500,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/wholegrain-bread",
    inStock: true,
    nutrition: { caloriesPer100g: 247, proteinPer100g: 13, carbsPer100g: 41, fatPer100g: 3.4, fiberPer100g: 7 },
  },
  {
    ebagId: "sweet-potato-1",
    name: "Sweet Potatoes",
    nameBg: "Сладки картофи",
    category: "vegetables",
    price: 2.99,
    originalPrice: 3.99,
    discountPct: 25,
    unit: "kg",
    weightGrams: 1000,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/sweet-potato",
    inStock: true,
    nutrition: { caloriesPer100g: 86, proteinPer100g: 1.6, carbsPer100g: 20, fatPer100g: 0.1, fiberPer100g: 3 },
  },
  {
    ebagId: "lentils-1",
    name: "Green Lentils",
    nameBg: "Зелена леща",
    category: "legumes",
    price: 3.99,
    originalPrice: 5.49,
    discountPct: 27,
    unit: "pcs",
    weightGrams: 500,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/lentils",
    inStock: true,
    nutrition: { caloriesPer100g: 352, proteinPer100g: 25, carbsPer100g: 60, fatPer100g: 1, fiberPer100g: 11 },
  },
  {
    ebagId: "beans-white-1",
    name: "White Beans",
    nameBg: "Бял боб",
    category: "legumes",
    price: 2.99,
    originalPrice: 3.79,
    discountPct: 21,
    unit: "pcs",
    weightGrams: 500,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/white-beans",
    inStock: true,
    nutrition: { caloriesPer100g: 333, proteinPer100g: 23, carbsPer100g: 60, fatPer100g: 0.8, fiberPer100g: 15 },
  },
  {
    ebagId: "pasta-whole-1",
    name: "Whole Wheat Pasta",
    nameBg: "Пълнозърнести макарони",
    category: "grains",
    price: 2.49,
    originalPrice: 3.19,
    discountPct: 22,
    unit: "pcs",
    weightGrams: 500,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/whole-pasta",
    inStock: true,
    nutrition: { caloriesPer100g: 348, proteinPer100g: 15, carbsPer100g: 64, fatPer100g: 2.5, fiberPer100g: 7 },
  },
  {
    ebagId: "bananas-1",
    name: "Bananas",
    nameBg: "Банани",
    category: "fruits",
    price: 2.29,
    originalPrice: 2.99,
    discountPct: 23,
    unit: "kg",
    weightGrams: 1000,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/bananas",
    inStock: true,
    nutrition: { caloriesPer100g: 89, proteinPer100g: 1.1, carbsPer100g: 23, fatPer100g: 0.3, fiberPer100g: 2.6 },
  },

  // === FAT SOURCES ===
  {
    ebagId: "olive-oil-1",
    name: "Extra Virgin Olive Oil",
    nameBg: "Зехтин екстра върджин",
    category: "oils",
    price: 12.99,
    originalPrice: 16.99,
    discountPct: 24,
    unit: "pcs",
    weightGrams: 1000,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/olive-oil",
    inStock: true,
    nutrition: { caloriesPer100g: 884, proteinPer100g: 0, carbsPer100g: 0, fatPer100g: 100, fiberPer100g: 0 },
  },
  {
    ebagId: "almonds-1",
    name: "Raw Almonds",
    nameBg: "Сурови бадеми",
    category: "nuts_seeds",
    price: 5.99,
    originalPrice: 7.99,
    discountPct: 25,
    unit: "pcs",
    weightGrams: 200,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/almonds",
    inStock: true,
    nutrition: { caloriesPer100g: 579, proteinPer100g: 21, carbsPer100g: 22, fatPer100g: 50, fiberPer100g: 12 },
  },
  {
    ebagId: "avocado-1",
    name: "Avocado (2 pcs)",
    nameBg: "Авокадо (2 бр)",
    category: "fruits",
    price: 3.49,
    originalPrice: 4.49,
    discountPct: 22,
    unit: "pcs",
    weightGrams: 400,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/avocado",
    inStock: true,
    nutrition: { caloriesPer100g: 160, proteinPer100g: 2, carbsPer100g: 9, fatPer100g: 15, fiberPer100g: 7 },
  },
  {
    ebagId: "butter-1",
    name: "Butter 82%",
    nameBg: "Масло 82%",
    category: "dairy",
    price: 4.99,
    originalPrice: 6.49,
    discountPct: 23,
    unit: "pcs",
    weightGrams: 250,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/butter",
    inStock: true,
    nutrition: { caloriesPer100g: 717, proteinPer100g: 0.9, carbsPer100g: 0.1, fatPer100g: 81, fiberPer100g: 0 },
  },

  // === VEGETABLES (fiber + micronutrients) ===
  {
    ebagId: "broccoli-1",
    name: "Broccoli",
    nameBg: "Броколи",
    category: "vegetables",
    price: 3.49,
    originalPrice: 4.99,
    discountPct: 30,
    unit: "kg",
    weightGrams: 1000,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/broccoli",
    inStock: true,
    nutrition: { caloriesPer100g: 34, proteinPer100g: 2.8, carbsPer100g: 7, fatPer100g: 0.4, fiberPer100g: 2.6 },
  },
  {
    ebagId: "spinach-1",
    name: "Fresh Spinach",
    nameBg: "Пресен спанак",
    category: "vegetables",
    price: 2.99,
    originalPrice: 3.99,
    discountPct: 25,
    unit: "pcs",
    weightGrams: 400,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/spinach",
    inStock: true,
    nutrition: { caloriesPer100g: 23, proteinPer100g: 2.9, carbsPer100g: 3.6, fatPer100g: 0.4, fiberPer100g: 2.2 },
  },
  {
    ebagId: "tomatoes-1",
    name: "Tomatoes",
    nameBg: "Домати",
    category: "vegetables",
    price: 2.49,
    originalPrice: 3.29,
    discountPct: 24,
    unit: "kg",
    weightGrams: 1000,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/tomatoes",
    inStock: true,
    nutrition: { caloriesPer100g: 18, proteinPer100g: 0.9, carbsPer100g: 3.9, fatPer100g: 0.2, fiberPer100g: 1.2 },
  },
  {
    ebagId: "cucumbers-1",
    name: "Cucumbers",
    nameBg: "Краставици",
    category: "vegetables",
    price: 1.99,
    originalPrice: 2.79,
    discountPct: 29,
    unit: "kg",
    weightGrams: 1000,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/cucumbers",
    inStock: true,
    nutrition: { caloriesPer100g: 15, proteinPer100g: 0.7, carbsPer100g: 3.6, fatPer100g: 0.1, fiberPer100g: 0.5 },
  },
  {
    ebagId: "peppers-1",
    name: "Bell Peppers (mixed)",
    nameBg: "Чушки (микс)",
    category: "vegetables",
    price: 3.99,
    originalPrice: 5.29,
    discountPct: 25,
    unit: "kg",
    weightGrams: 1000,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/peppers",
    inStock: true,
    nutrition: { caloriesPer100g: 31, proteinPer100g: 1, carbsPer100g: 6, fatPer100g: 0.3, fiberPer100g: 2.1 },
  },
  {
    ebagId: "carrots-1",
    name: "Carrots",
    nameBg: "Моркови",
    category: "vegetables",
    price: 1.49,
    originalPrice: 1.99,
    discountPct: 25,
    unit: "kg",
    weightGrams: 1000,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/carrots",
    inStock: true,
    nutrition: { caloriesPer100g: 41, proteinPer100g: 0.9, carbsPer100g: 10, fatPer100g: 0.2, fiberPer100g: 2.8 },
  },
  {
    ebagId: "apples-1",
    name: "Apples",
    nameBg: "Ябълки",
    category: "fruits",
    price: 2.49,
    originalPrice: 3.19,
    discountPct: 22,
    unit: "kg",
    weightGrams: 1000,
    imageUrl: "/images/placeholder-food.svg",
    ebagUrl: "https://ebag.bg/product/apples",
    inStock: true,
    nutrition: { caloriesPer100g: 52, proteinPer100g: 0.3, carbsPer100g: 14, fatPer100g: 0.2, fiberPer100g: 2.4 },
  },
];
